version: 2.1
aliases:
  - &workflow-name-continuous "Continuous deployment workflow"
  - &workflow-name-generate "Generate client workflow"
  - &workflow-name-publish "Publish client workflow"
  - &job-name-build "Build client"
  - &job-name-test "Test client"
  - &job-name-generate "Generate client"
  - &job-name-publish "Publish client"
  - &context-cloud "cloud_deployment"
  - &branch-trigger "trigger"
  - &branch-filter-publish '/^v[0-9]+\.[0-9]+$/'
  - &image-name "europe-docker.pkg.dev/dk-gg-rgstry/base/node:dev"
parameters:
  run_workflow_generate:
    default: false
    type: boolean
  openapi_url:
    type: string
    default: ""
executors:
  node-dev:
    parameters:
      image-name:
        type: string
        default: *image-name
    docker:
      - image: <<parameters.image-name>>
        auth:
          username: _json_key
          password: $GCLOUD_SERVICE_ACCOUNT
  git:
    docker:
      - image: alpine/git:latest
jobs:
  *job-name-build :
    working_directory: ~/build/project
    executor: node-dev
    steps:
      - checkout:
          name: Checkout source code
      - restore_cache:
          name: Restore node cache
          keys:
            - npm-dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          name: Save node cache
          paths:
            - node_modules
          key: npm-dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: ESLint
          command: npm run lint
      - run:
          name: Build
          command: npm run build
      - persist_to_workspace:
          root: /app/build/project
          paths:
            - .
  *job-name-test :
    working_directory: ~/build/project
    executor: node-dev
    steps:
      - attach_workspace:
          at: ~/build/project
      - run:
          name: Create folder for tests
          command: mkdir -p ~/testresults
      - run:
          name: Unit tests
          command: |
            npm run test \
              --json \
              --outputFile=~/testresults/jest.json
      - store_test_results:
          path: ~/testresults
      - store_artifacts:
          path: ~/testresults
  *job-name-generate :
    executor: node-dev
    working_directory: ~/build/project
    steps:
      - run:
          name: Check requirements
          command: |
            if [ -z "<<pipeline.parameters.openapi_url>>" ]; then
              echo "Missing pipeline.parameters.openapi_url"
              exit 1
            fi
      - checkout:
          name: Checkout repository
      - run:
          name: Download the new openapi.json
          command: |
            curl -s -o openapi.json <<pipeline.parameters.openapi_url>>
      - run:
          name: Check for openapi changes
          command: |
            set +e
            git diff --name-only --exit-code --quiet openapi.json
            if [ "$?" -ne 1 ]; then
              echo "No changes in openapi.json detected -> skipping client generation."
              # stop further execution of this job
              circleci-agent step halt
            fi
      - run:
          name: Prepare ssh config
          command: |
            mkdir -p ~/.ssh
            touch ~/.ssh/known_hosts
            ssh-keyscan -H bitbucket.org >> ~/.ssh/known_hosts
            touch ~/.ssh/bitbucket_private_key
            echo $BITBUCKET_PRIVATE_SSH_KEY | base64 -d >> ~/.ssh/bitbucket_private_key
            chmod 400 ~/.ssh/bitbucket_private_key
      - restore_cache:
          name: Restore node cache
          keys:
            - npm-dev-{{ checksum "package-lock.json" }}
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          name: Save dev vendor cache
          paths:
            - node_modules
          key: npm-dev-{{ checksum "package-lock.json" }}
      - run:
          name: Generate the client
          command: |
            npm run generate
      - run:
          name: Build the client
          command: |
            npm run build
      - run:
          name: Add changes to git commit stage
          command: |
            git add -A
      - run:
          name: Check for client changes
          command: |
            set +e
            changes=$(git diff --cached --name-only | grep -v -w "^openapi.json$")
            if [ -z "$changes" ]; then
              echo "No changes in the generated client code detected -> skipping commit."
              # stop further execution of this job
              circleci-agent step halt
            fi
      - run:
          name: Commit and push to approval branch
          command: |
            git config user.email $BITBUCKET_USER_EMAIL
            git config user.name $BITBUCKET_USER_NAME
            eval "$(ssh-agent -s)"
            ssh-add ~/.ssh/bitbucket_private_key
            
            APPROVAL_BRANCH_NAME="approval/${CIRCLE_BRANCH}/$(date +%Y%m%d-%H%M%S)_${CIRCLE_BUILD_NUM}"
            git checkout -b ${APPROVAL_BRANCH_NAME}
            git commit -m 'Autogenerated client update [publish]'
            git push --set-upstream origin ${APPROVAL_BRANCH_NAME}
  *job-name-publish :
    executor: node-dev
    working_directory: ~/build/project
    steps:
      - checkout:
          name: Checkout source code
      - run:
          name: Check for changes
          command: |
            lastTag=$(git describe --tags --abbrev=0)
            set +e
            # check if any commits starting with the last tag have the [publish] in their commit message  
            git log tags/${lastTag}.. --oneline --grep='\[publish\]' --exit-code
            if [ "$?" -ne 1 ]; then
              echo "No changes marked with [publish] between tags/${lastTag} and HEAD -> skipping publishing."
              # stop further execution of this job
              circleci-agent step halt
            fi
      - run:
          name: Authenticate with npm registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/build/project/.npmrc
      - run:
          name: Prepare ssh config
          command: |
            mkdir -p ~/.ssh
            touch ~/.ssh/known_hosts
            ssh-keyscan -H bitbucket.org >> ~/.ssh/known_hosts
            touch ~/.ssh/bitbucket_private_key
            echo $BITBUCKET_PRIVATE_SSH_KEY | base64 -d >> ~/.ssh/bitbucket_private_key
            chmod 400 ~/.ssh/bitbucket_private_key
      - run:
          name: Bump git tag and npm package version to next minor and push new tag
          command: |
            git config user.email $BITBUCKET_USER_EMAIL
            git config user.name $BITBUCKET_USER_NAME
            eval "$(ssh-agent -s)"
            ssh-add ~/.ssh/bitbucket_private_key

            lastTag=$(git describe --tags --abbrev=0)
            echo "Previous version: ${lastTag}"
            nextTag=$(echo $lastTag | awk -F. '{OFS="."; $NF+=1; print $0}')
            
            echo "Publishing with tag ${nextTag}"
            git tag -a $nextTag -m "Autogenerated client update ${nextTag}"
            npm version from-git -m "Bumped package version to %s" --allow-same-version

            git push origin
            git push origin tags/$nextTag
      - run:
          name: Publish npm package
          command: npm publish --access public
workflows:
  version: 2
  *workflow-name-continuous :
    jobs:
      - *job-name-build :
          context: *context-cloud
          filters:
            branches:
              ignore:
                - *branch-filter-publish
                - *branch-trigger
      - *job-name-test :
          context: *context-cloud
          requires:
            - *job-name-build
          filters:
            branches:
              ignore:
                - *branch-filter-publish
                - *branch-trigger
  *workflow-name-generate :
    when: <<pipeline.parameters.run_workflow_generate>>
    jobs:
      - *job-name-generate :
          context: *context-cloud
          filters:
            branches:
              only: *branch-filter-publish
  *workflow-name-publish :
    jobs:
      - *job-name-build :
          context: *context-cloud
          filters:
            branches:
              only: *branch-filter-publish
      - *job-name-test :
          context: *context-cloud
          requires:
            - *job-name-build
          filters:
            branches:
              only: *branch-filter-publish
      - *job-name-publish :
          context: *context-cloud
          requires:
            - *job-name-test
          filters:
            branches:
              only: *branch-filter-publish
